FROM node:alpine as development
WORKDIR /app
RUN npm install -g pnpm
COPY package.json .
RUN pnpm i 
COPY . .
RUN pnpm build

FROM node:alpine as production
EXPOSE 4000
WORKDIR /app
RUN npm install -g pnpm
COPY package.json ./
COPY .env ./
COPY --from=development /app/dist ./dist
RUN pnpm i --prod && pnpm store prune
CMD ["pnpm","run","start:prod"]