# To bring up an environment, first define it: export ENV=dev
# DEV - Next bring up the environment with its respective yml file: docker-compose up

version: "3.7"

services:
  snappymail:
    image: djmaze/snappymail
    container_name: snappymail
    volumes:
      - /opt/snappymail:/var/lib/snappymail
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - env/snappymail.env
    networks:
      - www

  # service:
  #   container_name: service
  #   image: bmccorm2/service
  #   restart: on-failure
  #   depends_on:
  #     - db
  #   env_file:
  #     - env/service.env
  #   networks:
  #     - www

  # web:
  #   container_name: web
  #   image: bmccorm2/web
  #   restart: on-failure
  #   env_file:
  #     - env/web.env
  #   networks:
  #     - www

  nextcloud:
    container_name: nextcloud
    image: nextcloud:fpm-alpine
    volumes:
      - /opt/nextcloud:/var/www/html
      - /etc/localtime:/etc/localtime:ro
    restart: always
    env_file:
      - env/nextcloud.${ENV}.env
    networks:
      - www

  nc-web:
    build: ./nc-web
    container_name: nc-web
    restart: always
    env_file:
      - env/nc-web.${ENV}.env
    volumes:
      - /opt/nextcloud:/var/www/html:ro
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - nextcloud
    networks:
      - www

networks:
  www:
    external: true
